version: "3.9"
services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes: 
      - type: bind
        source: C:\SAPDevelop\organization-chart-2023
        target: /opt/organization-chart-2023