###
GET http://localhost:5000/user/Us HTTP/1.1

###
POST http://localhost:4004/user/Us HTTP/1.1
Content-Type: application/json

{
  "isLead": true,
  "company": "SAP",
  "title": "Senior Max Attention Engineer",
  "firstname": "Ashok",
  "lastname": "Kumar"
}

###
PATCH http://localhost:4004/user/Us/fec7fcc1-ad49-4218-95d1-07f34a70d62b HTTP/1.1
Content-Type: application/json

{
    "manager_ID": "dc36f8e6-7056-47b3-ac4e-4a9e487fc817"
}

###
GET http://localhost:4004/user/Us/fec7fcc1-ad49-4218-95d1-07f34a70d62b/manager HTTP/1.1

###
GET http://localhost:4004/user/Us/dc36f8e6-7056-47b3-ac4e-4a9e487fc817/members HTTP/1.1